[package]
name = "diceware-rust"
version = "0.2.0"
authors = ["Jacob Morzinski <jmorzins@mit.edu>"]
description = "Print random words from the diceware list"
edition = "2018"

[dependencies]
derive_more = "*"
rand = "0.7.2"

[dependencies.clap]
version = "~2.32"
default-features = false
