[package]
name = "diceware-rust"
version = "0.1.0"
authors = ["Jacob Morzinski <jmorzins@mit.edu>"]
description = "Print random words from the diceware list"
edition = "2018"

[dependencies]
rand = "0.6.5"

[dependencies.clap]
version = "~2.32"
default-features = false
